### ISSUE TITLE
Lottery issues

### ISSUE THREAD

**Issue by Sherali5543** [CMPUT301F24napkin/napkinfactory#122]
- Lottery toasts suck
- Should not be able to lottery people again until some of the chosen reject or are manually rejected
-- This would also require the size of the lottery to be reduced

**Comment by antoszko** [comment]
I disagree, you should be able to lottery as soon as the waitlist is non-empty and registered+chosen < participantLimit.
I will fix toasts tho

**Comment by Sherali5543** [comment]
as long as registered+chosen < participant limit is actually being checked, I agree
