### ISSUE TITLE
Rotating the screen breaks it

### ISSUE THREAD

**Issue by antoszko** [CMPUT301F24napkin/napkinfactory#15]
Tested on the footer-functionality branch.
To reproduce, run simulator, click the rotate screen button, observe.

I would suggest disabling rotating the screen altogether in the interest of time.

**Comment by Sherali5543** [comment]
no it doesnt? It works fine when i rotate it

**Comment by antoszko** [comment]
Mine doesn't for some reason. Anyways I locked it to portrait only in #35
