### ISSUE TITLE
Abs ur key generation method doesn't work

### ISSUE THREAD

**Issue by antoszko** [CMPUT301F24napkin/napkinfactory#17]
ur setting the key of the next item to be the number of docs currently in the db. If you remove any but the last document and then try to create one again, you will overwrite data

**Comment by antoszko** [comment]
@Deenknight

**Comment by Deenknight** [comment]
Ah the code for createEventFragment was mostly just to demonstrate the db working. It will have to be changed in the final product because the Event model will need all fields

**Comment by Deenknight** [comment]
I am going to add a writeData overload method that returns the generated id from firestore. So you can either specify the id and overwrite the data, or let firestore generate it and return it to you.

**Comment by Deenknight** [comment]
#19
